name: "GitHub → GitLab Sync"
description: "Syncs the current branch to GitLab"

inputs:
  token:
    description: >
      Token for pushing to GitLab which can be created in Gitlab under
      Settings > Access Tokens. Uses the secret `GITLAB_TOKEN` by default.
    required: true

  owner:
    description: >
      GitLab owner or group name. If not provided, the default is the owner of
      the current Github repository.
    required: false
    default: "${{ github.repository_owner }}"

  repository_name:
    description: >
      GitLab repository name. If not provided, the default is the name of the
      current Github repository.
    required: false
    default: "${{ github.event.repository.name }}"

  branch:
    description: >
      Branch to push to in the GitLab repository. If not provided, the default
      is the current branch.
    required: false
    default: "${{ github.ref_name }}"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Add GitLab remote
      run: git remote add gitlab https://oauth2:${{ inputs.token }}@gitlab.com/${{ inputs.owner }}/${{ inputs.repository_name }}.git
      shell: bash

    - name: Push to GitLab
      run: git push -f gitlab ${{ inputs.branch }}
      shell: bash
