name: Test this action
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run action to sync to GitLab
        uses: kulla/sync-to-gitlab@main
        with:
          gitlab_owner: stephan_kulla
